---
title: MUCK NEWS
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    permalink: "/:name"
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/project/:slug"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: projects
  values:
    layout: project
site: MUCK NEWS
url: 
baseurl: 
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  style: compressed
plugins:
- jekyll-sitemap
paginate: 7
paginate_path: "/blog/page-:num/"
